config/routes.rb
Rails.application.routes.draw do

  resources :doctors do
    collection do
      get 'list_male'
      get 'list_female'
    end
  end

  root 'doctors#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doctor.rb
class Doctor < ApplicationRecord

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :address, presence: true
  validates :gender, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]

  def new
    @doctor = Doctor.new
  end

  def show

  end

  def index
    @doctors = Doctor.all
  end

  def edit
  end

  def update
    @doctor.update(doctor_params)
    redirect_to doctor_path(@doctor)
  end

  def create
    @doctor = Doctor.new(doctor_params)
    if @doctor.save
      redirect_to doctor_path(@doctor)
    else
      render :new
    end
  end

  def destroy
    @doctor.destroy
    redirect_to doctors_path
  end

  def list_male
    @doctors = Doctor.where(gender: "Male")
  end

  def list_female
    @doctors = Doctor.where(gender: "Female")
  end

  private

  def set_doctor
    @doctor = Doctor.find(params[:id])
  end

  def doctor_params
    params.require(:doctor).permit(:last_name, :first_name, :address, :gender)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/_form.html.erb
<%= simple_form_for @doctor do |f| %>
  <div class="form-inputs">
    <%= f.input :first_name %>
  </div>
  <div class="form-inputs">
    <%= f.input :last_name %>
  </div>
  <div class="form-inputs">
    <%= f.input :address, as: :text %>
  </div>
  <div class="form-inputs">
    <%= f.input :gender, collection: ["Male", "Female"] %>
  </div>
  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/doctors/_list.html.erb
  <table class="table">
    <% @doctors.each_with_index do |doctor, index| %>
      <tr>
        <td><%= index+1 %>
      </td>
        <td>
          <%= link_to doctor.first_name, doctor_path(doctor) %>
        </td>
        <td>
          <%= link_to 'Edit', edit_doctor_path(doctor) %>
        </td>
        <td>
          <%= link_to 'Delete', doctor_path(doctor), method: :delete %>
        </td>
      </tr>
    <% end %>
  </table>

app/views/doctors/create.html.erb
<h1>Doctors#create</h1>
<p>Find me in app/views/doctors/create.html.erb</p>

app/views/doctors/destroy.html.erb
<h1>Doctors#destroy</h1>
<p>Find me in app/views/doctors/destroy.html.erb</p>

app/views/doctors/edit.html.erb
<h1>Doctors#edit</h1>
<p>Find me in app/views/doctors/edit.html.erb</p>

<%= render 'form' %>

app/views/doctors/index.html.erb
<h1>All Doctors</h1>
<p>Find me in app/views/doctors/index.html.erb</p>
<div class="panel panel-default">
  <%= render 'list' %>
</div>

app/views/doctors/list_female.html.erb
<h1>Female Doctors</h1>

<%= render 'list' %>

app/views/doctors/list_male.html.erb
<h1>Male Doctors</h1>

<%= render 'list' %>

app/views/doctors/new.html.erb
<h1>Doctors#new</h1>
<p>Find me in app/views/doctors/new.html.erb</p>

<%= render 'form' %>

app/views/doctors/show.html.erb
<h1>Doctor</h1>
<table class="table">
  <tr>
    <td>
      Firstname
    </td>
    <td>
    <%= @doctor.first_name %>
    </td>
  </tr>
  <tr>
    <td>
      Lastname
    </td>
    <td>
    <%= @doctor.last_name %>
    </td>
  </tr>
  <tr>
    <td>
      Address
    </td>
    <td>
    <%= @doctor.address %>
    </td>
  </tr>
  <tr>
    <td>
      Gender
    </td>
    <td>
    <%= @doctor.gender %>
    </td>
  </tr>

app/views/doctors/update.html.erb
<h1>Doctors#update</h1>
<p>Find me in app/views/doctors/update.html.erb</p>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <ul class="nav navbar-nav">
      <li>
        <%= link_to 'Home', root_path %>
      </li>
      <li>
        <% if user_signed_in? %>
          <li>
            <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
          </li>
          <li>
            <%= link_to 'Male Doctors', list_male_doctors_path %>
          </li>
          <li>
            <%= link_to 'Female Doctors', list_female_doctors_path %>
          </li>
          <li>
            <%= link_to 'New Doctor', new_doctor_path %>
          </li>
        <% else %>
          <li>
            <%= link_to 'Login', new_user_session_path %>
          </li>
        <% end %>

    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyAcMidtermAssessment</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/nav' %>
    <div class="container">
      <div class="col-md-8 col-md-offset-2">
      <%= yield %>
      </div>
    </div>
  </body>
</html>